= 카테고리 관리 API

== 카테고리 추가

=== 성공

==== 카테고리 추가 성공

operation::category-admin-controller-test/add-category[snippets="curl-request,http-request,http-response"]

==== 카테고리 추가 성공 - 없는 부모 카테고리 입력

operation::category-admin-controller-test/add-category-with-not-exist-parent-category[snippets="curl-request,http-request,http-response"]

=== 실패

==== 카테고리 추가 실패 - 관리자 권한 없음

operation::category-admin-controller-test/add-category-with-not-admin[snippets="curl-request,http-request,http-response"]

== 카테고리 조회

=== 성공

==== 관리자 카테고리 관리 페이지 조회 성공

operation::category-admin-controller-test/get-categories[snippets="curl-request,http-request,http-response"]

=== 실패

==== 관리자 카테고리 조회 실패 - 관리자 권한 없음

operation::category-admin-controller-test/get-categories-with-not-admin[snippets="curl-request,http-request,http-response"]

== 카테고리 수정

=== 성공

==== 카테고리 수정 성공

operation::category-admin-controller-test/modify-category-successfully[snippets="curl-request,http-request,http-response"]

=== 실패

==== 카테고리 수정 실패 - 사용자 ID 없음

operation::category-admin-controller-test/modify-category-fails-when-user-id-is-missing[snippets="curl-request,http-request,http-response"]

==== 카테고리 수정 실패 - 관리자 권한 없음

operation::category-admin-controller-test/modify-category-fails-when-not-admin[snippets="curl-request,http-request,http-response"]

== 카테고리 삭제

=== 성공

==== 카테고리 삭제 성공

operation::category-admin-controller-test/remove-category-successfully[snippets="curl-request,http-request,http-response"]

=== 실패

==== 카테고리 삭제 실패 - 사용자 ID 없음

operation::category-admin-controller-test/remove-category-fails-when-user-id-is-missing[snippets="curl-request,http-request,http-response"]

==== 카테고리 삭제 실패 - 관리자 권한 없음

operation::category-admin-controller-test/remove-category-fails-when-not-admin[snippets="curl-request,http-request,http-response"]

== 카테고리 삭제 복구

=== 성공

==== 카테고리 삭제 복구 성공

operation::category-admin-controller-test/restore-category-successfully[snippets="curl-request,http-request,http-response"]

=== 실패

==== 카테고리 삭제 복구 실패 - 사용자 ID 없음

operation::category-admin-controller-test/restore-category-fails-when-user-id-is-missing[snippets="curl-request,http-request,http-response"]

==== 카테고리 삭제 복구 실패 - 관리자 권한 없음

operation::category-admin-controller-test/restore-category-fails-when-not-admin[snippets="curl-request,http-request,http-response"]